#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME

domain=$(ynh_app_setting_get $app domain)

#=================================================
# STANDARD REMOVE
#=================================================
# STOP AND REMOVE SERVICE
#=================================================

# Remove the uwsgi configuration
systemctl stop uwsgi
if [ -h "/etc/uwsgi/apps-enabled/$app.ini" ]; then
	echo "Delete uwsgi config"
	ynh_secure_remove "/etc/uwsgi/apps-enabled/$app.ini"
fi
ynh_secure_remove "/etc/uwsgi/apps-available/$app.ini"

#=================================================
# REMOVE DEPENDENCIES
#=================================================

ynh_remove_app_dependencies

#=================================================
# REMOVE THE MAIN DIR OF THE APP
#=================================================

ynh_secure_remove "/opt/yunohost/$app"

#=================================================
# REMOVE THE NGINX CONFIGURATION
#=================================================

# Remove the dedicated nginx config
ynh_remove_nginx_config

#=================================================
# DISABLE SERVICE IN ADMIN PANEL
#=================================================

if [ -e /etc/init.d/uwsgi ]
then
	# Redémarre le service uwsgi si il n'est pas désinstallé.
	systemctl start uwsgi
else
	if yunohost service status | grep -q uwsgi	# Test l'existence du service dans Yunohost
	then
		echo "Remove uwsgi service"
		yunohost service remove uwsgi
	fi
fi

#=================================================
# GENERIC FINALISATION
#=================================================
# REMOVE DEDICATED USER
#=================================================

# Delete a system user
ynh_system_user_delete $app
